sudo: required
language: minimal
python: 2.7

services:
  - docker

env:
  matrix:
  - TOX_ENV=py27
  global:
  - secure: "RKgV6kgv1ICwF257WYXwygfzNUPBPRUrkPSbMsxOxpWoJMYgTlmKMmOhvGTbrbmK0nAtRkNigaev7hqmY9GpkgtWRQct5xnccTcb9g6koWsZs7S/dI2DSfFryZAtcHiLC2Jgvo6AOcTLSk4ijhpEElLBozuxCr4p88BGoZ9QShjoTEA7z6befnKPNbJa9p9BLcrUFoCNN+6ScqCyTk9TksPeqgmd4s93LPWk33GhkrK/LcK6M+F4C3KTLCV56WwzTneqeTPrdeab4IctCz5uizB57Lf5Jt/a4wX7loQfy2DeiqcG0jOCTnNNLrfFBgxzBBrqUmyuUHdNwnS6jl8lV68LFUOKvvPulOVO/PM3qxDbSoNTPWgKJmO+ykosmB0i/K4PAJkLQTHRgIjy+XLnN7MGEguFYOTtvQ3jdVW0dxj34x0wJ1omMm47TDzvtLr4JeHdMQngag4cNvI8tgsRoI4N3ALi7qJmGptlWQx7bZrxl20rF4fTEpIPSEHPVt5laH64hnFBvfadcPFe5hRRXsoBIdZTciVe44EF/zs3PWeNLEdFDQfYfcGXSveIkyMpV4soVf1vz4+kvQx+r9PEun84cHhfLpAMl/cloX6GqlRWbqtc8HOWy8YZu66Wa6zoUSVrfsJA33s/n+EJyJLHZe4uvL1XE2JU/lS9QLLC3lc="

before_install:
  - wget https://raw.githubusercontent.com/bgruening/galaxy-flavor-testing/master/Makefile
  - make docker_install
  - sudo apt-get -qq update
  - sudo apt-get install -y python-dev
  - travis_wait 75 make docker_build
  - make docker_run
  - sleep 60

install:
  - make install

script:
  - make test_api
  - make test_ftp
  - make test_bioblend
  #- make test_docker_in_docker

after_success:
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]
    then
      echo "Generate and deploy html website"
      ./bin/deploy_website
    fi

